Mark deprecated SSL settings as obsolete
logstash-plugins/logstash-output-tcp pull request #58
Opened 2024-12-02 14:47 UTC by robbavey

This commit marks the following SSL settings as obsolete:

`ssl_cert`, which should be replaced by `ssl_certificate`
`ssl_cacert`, which should be replaced by `ssl_certificate_authorities`
`ssl_enable`, which should be replaced by `ssl_enabled`
`ssl_verify`, which should be replaced by `ssl_client_authentication` when `mode` is `server` or `ssl_verification_mode`when mode is `client`

2024-12-09 20:57 UTC, donoghuc commented on lib/logstash/outputs/tcp.rb
> +    # setup_ssl_params!
I think we can just stop overriding the init method from the base class now. So probably just delete the entire `initialize` method.

2024-12-09 20:59 UTC, donoghuc requested changes
Overall removal looks completed. Just a few minor review comments I think are worth addressing.

2024-12-09 22:31 UTC, donoghuc commented on lib/logstash/outputs/tcp.rb
>    end
```suggestion
```
I suggest we stop overriding inherited `initialize` method.

2024-12-09 22:31 UTC, donoghuc commented on lib/logstash/outputs/tcp.rb
> +    # setup_ssl_params!
Added this as a GH suggestion for ease of commit if you agree :) https://github.com/logstash-plugins/logstash-output-tcp/pull/58/files#r1876854779

2024-12-09 23:58 UTC, donoghuc commented on spec/outputs/tcp_spec.rb
> +  describe 'handling obsolete settings for server mode' do
Are we missing some config to construct server vs client mode? I cant see how these are different.

2024-12-10 21:22 UTC, robbavey commented
Ready for docs review @karenzone

2024-12-16 18:14 UTC, donoghuc requested changes
Changelog formatting update (in suggestion).

2024-12-16 18:14 UTC, donoghuc commented on CHANGELOG.md
> +
```suggestion
  - SSL settings that were marked deprecated in version `6.2.0` are now marked obsolete, and will prevent the plugin from starting.
  - These settings are:
      - `ssl_cert`, which should be replaced by `ssl_certificate`
      - `ssl_cacert`, which should be replaced by `ssl_certificate_authorities`
      - `ssl_enable`, which should be replaced by `ssl_enabled`
      - `ssl_verify`, which should be replaced by `ssl_client_authentication` when `mode` is `server` or `ssl_verification_mode`when mode is `client`
      - [58](https://github.com/logstash-plugins/logstash-output-tcp/pull/58)
```

2024-12-16 19:35 UTC, donoghuc approved these changes

2024-12-23 18:17 UTC, karenzone commented on docs/index.asciidoc
> +and have been replaced by the following options:
```suggestion
WARNING: As of version `6.0.0` of this plugin, some configuration options have been replaced.
The plugin will fail to start if it contains any of these obsolete options. 
```

2024-12-23 18:18 UTC, karenzone reviewed
Left suggestion inline to align with docs for other plugins

2025-01-03 18:24 UTC, robbavey commented
Ready for another round @karenzone

2025-01-09 23:31 UTC, karenzone approved these changes
LGTM

2025-01-10 19:31 UTC, merged